display_name: Scrcpy GUI

icon: assets/logo.png

keywords:
  - scrcpy
  - gui

generic_name: Scrcpy GUI

categories: 
  - Utility

startup_notify: true

include: 
  - libayatana-appindicator3.so.1
  - libayatana-indicator3.so.7
  - libayatana-ido3-0.4.so.0