on: 
  push:
    branches:
    - dev

jobs:
  mac:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.32.4
      - run: flutter pub get
      - run: flutter build macos --release
  linux: 
    runs-on: ubuntu-22.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.32.4
      - run: sudo apt-get install libayatana-appindicator3-dev   
      - run: flutter pub get
      - run: flutter build linux --release
  windows: 
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.32.4
      - run: flutter pub get
      - run: flutter build windows --release
    


      
